import subprocess
import os
import sys
import threading
import time
import tarfile
import shutil

# Handle Windows console encoding for emojis
if sys.platform == "win32":
    import codecs
    sys.stdout.reconfigure(encoding='utf-8')

# --- CONFIGURATION ---
SERVER_IP = "20.24.58.49"
SERVER_DIR = "/var/www/html/InsightED-SchoolHead/insighted-schoolhead"
USER = "Administrator1"
TAR_FILE = "schoolhead-deploy.tmp.tar.gz"
PORT = 5010
PM2_NAME = "insighted-schoolhead-backend"
ECOSYSTEM_CONFIG = "ecosystem.schoolhead.config.cjs"

INCLUDE = [
    "apps/school-head/api",
    "apps/siif/api",
    "dist",
    ".env",
    "package.json",
    "pnpm-lock.yaml",
    "pnpm-workspace.yaml",
    "turbo.json",
    "packages",
    ECOSYSTEM_CONFIG,
]

# --- COLORS ---
GREEN = '\033[0;32m'
RED = '\033[0;31m'
CYAN = '\033[0;36m'
YELLOW = '\033[1;33m'
NC = '\033[0m'

def info(msg): print(f"{CYAN}ℹ️   {msg}{NC}", flush=True)
def success(msg): print(f"{GREEN}✅ {msg}{NC}", flush=True)
def warn(msg): print(f"{YELLOW}⚠️   {msg}{NC}", flush=True)
def error(msg): print(f"{RED}❌ {msg}{NC}", flush=True)

SSH_OPTS = [
    "-o", "BatchMode=yes",
    "-o", "StrictHostKeyChecking=accept-new",
    "-o", "ConnectTimeout=10",
    "-o", "ServerAliveInterval=15",
    "-o", "ServerAliveCountMax=3"
]

def run_command(cmd, capture=False, retries=1, timeout=None, env=None):
    attempt = 0
    while attempt < retries:
        try:
            if isinstance(cmd, str):
                res = subprocess.run(cmd, shell=True, check=True, capture_output=capture, text=True, timeout=timeout, env=env)
            else:
                res = subprocess.run(cmd, check=True, capture_output=capture, text=True, timeout=timeout, env=env)
            return res
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
            attempt += 1
            if attempt < retries:
                warn(f"Command failed (attempt {attempt}/{retries}), retrying in 3s...")
                time.sleep(3)
            else:
                error(f"Command failed permanently: {cmd}")
                if capture and hasattr(e, 'stderr') and e.stderr:
                    print(f"{RED}{e.stderr}{NC}")
                raise e

def cleanup_local_archive():
    for attempt in range(1, 6):
        try:
            if os.path.exists(TAR_FILE):
                os.remove(TAR_FILE)
                info("Local temporary payload archive removed.")
            break
        except Exception:
            if attempt < 5:
                time.sleep(1.5)

def build_frontend():
    print(f"\n{YELLOW}🏗️   Phase 1: Building frontend (Base path: /insighted-schoolhead/)...{NC}", flush=True)
    env = os.environ.copy()
    env["VITE_BASE_PATH"] = "/insighted-schoolhead/"
    env["NODE_OPTIONS"] = "--max-old-space-size=4096"
    
    # Target SchoolHead web app directly to avoid unrelated missing package errors
    if sys.platform == "win32":
        cmd = "cd apps\\school-head\\web && pnpm build || npx vite build"
    else:
        cmd = "cd apps/school-head/web && pnpm build || npx vite build"
    run_command(cmd, env=env)
    
    src_dist = os.path.join("apps", "school-head", "web", "dist")
    dst_dist = "dist"
    if os.path.exists(src_dist):
        if os.path.exists(dst_dist):
            shutil.rmtree(dst_dist)
        shutil.copytree(src_dist, dst_dist)
        success("Synced apps/school-head/web/dist to root dist/.")
    elif not os.path.exists(dst_dist):
        error("dist/ folder was not generated by the build! Aborting.")
        sys.exit(1)
    success("Frontend build complete.")

def prepare_remote():
    print(f"\n{YELLOW}🧹 Phase 2: Preparing remote directory {SERVER_DIR}...{NC}", flush=True)
    ssh_target = f"{USER}@{SERVER_IP}"
    prep_cmd = f"sudo mkdir -p {SERVER_DIR}/logs && sudo chown -R {USER}:{USER} {SERVER_DIR}"
    ssh_cmd = ["ssh"] + SSH_OPTS + [ssh_target, prep_cmd]
    run_command(ssh_cmd, retries=5)
    success("Remote directory prepared.")

def package_archive():
    print(f"\n{YELLOW}📦 Phase 3: Creating payload archive...{NC}", flush=True)
    existing_includes = [item for item in INCLUDE if os.path.exists(item)]
    
    def exclude_filter(tarinfo):
        name = tarinfo.name.lower()
        if any(x in name for x in ["node_modules", ".git", ".turbo", ".agent"]):
            return None
        return tarinfo

    with tarfile.open(TAR_FILE, "w:gz") as tar:
        for item in existing_includes:
            tar.add(item, filter=exclude_filter)
            info(f"       + {item}")
    success("Payload archive created.")

def upload_and_deploy():
    print(f"\n{YELLOW}📤 Phase 4: Uploading archive and executing remote setup in {SERVER_DIR}...{NC}", flush=True)
    ssh_target = f"{USER}@{SERVER_IP}"
    
    scp_cmd = ["scp"] + SSH_OPTS + [TAR_FILE, f"{ssh_target}:{SERVER_DIR}/"]
    run_command(scp_cmd, retries=5)
    
    remote_setup = (
        f"cd {SERVER_DIR} && "
        f"tar -xzf {TAR_FILE} && "
        f"rm -f {TAR_FILE} && "
        f"sudo chmod -R 755 {SERVER_DIR} && "
        "export PATH=$PATH:/usr/local/bin:/home/Administrator1/.local/share/pnpm; "
        "echo '       -> Refreshing dependencies (pnpm install)...'; "
        "timeout 180 pnpm install --prod --prefer-offline 2>&1 | tail -n 10 || pnpm install --prefer-offline 2>&1 | tail -n 10; "
        f"pm2 flush {PM2_NAME} 2>/dev/null || true; "
        f"pm2 delete {PM2_NAME} 2>/dev/null || true; "
        f"pm2 delete insighted-siif-backend 2>/dev/null || true; "
        f"pm2 start {ECOSYSTEM_CONFIG} --update-env && "
        "pm2 save"
    )
    ssh_deploy_cmd = ["ssh"] + SSH_OPTS + [ssh_target, remote_setup]
    run_command(ssh_deploy_cmd, retries=1, timeout=180)
    success("Remote extraction and PM2 startup complete.")

def verify():
    print(f"\n{YELLOW}🔬 Phase 5: Verification & Auto-Revive{NC}", flush=True)
    ssh_target = f"{USER}@{SERVER_IP}"
    
    info("Checking PM2 status...")
    show_cmd = ["ssh"] + SSH_OPTS + [ssh_target, f"pm2 show {PM2_NAME} | grep status"]
    res = run_command(show_cmd, capture=True, retries=3)
    print(res.stdout, flush=True)

    info(f"Checking local health endpoint (port {PORT})...")
    health_cmd = ["ssh"] + SSH_OPTS + [ssh_target, f"curl -sf http://127.0.0.1:{PORT}/api/auth/me || curl -sf http://127.0.0.1:{PORT}/ || true"]
    run_command(health_cmd, capture=False, retries=3)

def main():
    start_time = time.time()
    print(f"{CYAN}" + "="*60 + f"{NC}", flush=True)
    print(f"{GREEN}🚀 InsightEd SchoolHead Production Deployment{NC}", flush=True)
    print(f"{CYAN}Target Path: {SERVER_DIR} | Port: {PORT}{NC}", flush=True)
    print(f"{CYAN}" + "="*60 + f"{NC}", flush=True)

    try:
        build_frontend()
        prepare_remote()
        package_archive()
        upload_and_deploy()
        verify()
    finally:
        cleanup_local_archive()

    duration = time.time() - start_time
    print(f"\n{GREEN}" + "="*60 + f"{NC}")
    success(f"Deployment to {SERVER_DIR} Complete in {duration:.2f}s!")
    print(f"    URL: https://stride.deped.gov.ph/insighted-schoolhead/")
    print(f"{GREEN}" + "="*60 + f"{NC}")

if __name__ == "__main__":
    main()
