import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * InsightEd Report Generator
 * Generates branded PDF reports and CSV exports for Super Users.
 */

const BRAND_COLOR = [0, 74, 153]; // #004A99
const LIGHT_BLUE = [230, 240, 255];
const DARK_TEXT = [30, 41, 59]; // slate-800

/**
 * Creates a branded PDF document with InsightEd header
 */
const createBrandedPDF = (title, context) => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const now = new Date();
    const timestamp = now.toLocaleString('en-PH', {
        year: 'numeric', month: 'long', day: 'numeric',
        hour: '2-digit', minute: '2-digit'
    });

    // --- Blue Header Bar ---
    pdf.setFillColor(...BRAND_COLOR);
    pdf.rect(0, 0, pageWidth, 38, 'F');

    // Title
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text('InsightEd Official Audit Report', 14, 16);

    // Subtitle - Context
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    const contextLine = `Generated by Super User — ${context.role}: ${context.location || 'National'}`;
    pdf.text(contextLine, 14, 24);

    // Date
    pdf.setFontSize(8);
    pdf.text(`Date: ${timestamp}`, 14, 31);

    // Report Type (right-aligned)
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text(title, pageWidth - 14, 16, { align: 'right' });

    // DepEd badge
    pdf.setFontSize(7);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Department of Education — Philippines', pageWidth - 14, 31, { align: 'right' });

    return { pdf, startY: 46, pageWidth };
};

/**
 * Adds page numbers to all pages
 */
const addPageNumbers = (pdf) => {
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150, 150, 150);
        pdf.text(
            `Page ${i} of ${totalPages}`,
            pdf.internal.pageSize.getWidth() / 2,
            pdf.internal.pageSize.getHeight() - 8,
            { align: 'center' }
        );
    }
};

// ============================================================================
//  MONITORING REPORT
// ============================================================================

export const generateMonitoringReport = (kpiData) => {
    const context = kpiData.context || {};
    const { pdf, startY, pageWidth } = createBrandedPDF('Monitoring Summary', context);

    let y = startY;

    // --- Section: School KPIs ---
    const schoolKpis = kpiData.school_kpis || {};

    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...DARK_TEXT);
    pdf.text('School Accomplishment Summary', 14, y);
    y += 8;

    // Summary cards row
    const summaryData = [
        ['Total Schools', String(schoolKpis.total_schools || 0)],
        ['Completed (100%)', String(schoolKpis.completed || 0)],
        ['Completion Rate', `${schoolKpis.completion_pct || 0}%`],
        ['Validated', String(schoolKpis.validated || 0)],
    ];

    autoTable(pdf, {
        startY: y,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 10, textColor: DARK_TEXT },
        alternateRowStyles: { fillColor: LIGHT_BLUE },
        margin: { left: 14, right: 14 },
        tableWidth: 'auto',
    });

    y = pdf.lastAutoTable.finalY + 12;

    // --- Section: Form Breakdown ---
    const forms = schoolKpis.form_breakdown || {};
    if (Object.keys(forms).length > 0) {
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Form Completion Breakdown', 14, y);
        y += 6;

        const formLabels = {
            profile: 'F1 - School Profile',
            head: 'F2 - School Head',
            enrollment: 'F3 - Enrollment',
            organizedclasses: 'F4 - Organized Classes',
            personnel: 'F5 - Teaching Personnel',
            specialization: 'F6 - Specialization',
            resources: 'F7 - School Resources',
            facilities: 'F8 - Facilities',
            shifting: 'F9 - Shifting/MISOSA',
            learner_stats: 'F10 - Learner Statistics',
        };

        const formData = Object.entries(formLabels).map(([key, label]) => {
            const count = forms[key] || 0;
            const total = schoolKpis.total_schools || 1;
            const pct = Math.min(100, ((count / total) * 100)).toFixed(1);
            return [label, String(count), `${pct}%`];
        });

        autoTable(pdf, {
            startY: y,
            head: [['Form', 'Submitted', '% Complete']],
            body: formData,
            theme: 'grid',
            headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
            bodyStyles: { fontSize: 9, textColor: DARK_TEXT },
            alternateRowStyles: { fillColor: LIGHT_BLUE },
            margin: { left: 14, right: 14 },
        });

        y = pdf.lastAutoTable.finalY + 12;
    }

    // --- Section: Engineer KPIs ---
    const engKpis = kpiData.engineer_kpis || {};
    if (engKpis.total_projects > 0) {
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Infrastructure Project Summary', 14, y);
        y += 6;

        const engData = [
            ['Total Projects', String(engKpis.total_projects || 0)],
            ['Completed', String(engKpis.completed || 0)],
            ['Ongoing', String(engKpis.ongoing || 0)],
            ['Not Yet Started', String(engKpis.not_yet_started || 0)],
            ['Under Procurement', String(engKpis.under_procurement || 0)],
            ['For Final Inspection', String(engKpis.for_final_inspection || 0)],
        ];

        autoTable(pdf, {
            startY: y,
            head: [['Metric', 'Count']],
            body: engData,
            theme: 'grid',
            headStyles: { fillColor: [234, 88, 12], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
            bodyStyles: { fontSize: 10, textColor: DARK_TEXT },
            alternateRowStyles: { fillColor: [255, 247, 237] },
            margin: { left: 14, right: 14 },
        });
    }

    addPageNumbers(pdf);
    pdf.save(`InsightEd_Monitoring_Report_${context.role?.replace(/\s+/g, '_') || 'Export'}_${new Date().toISOString().slice(0, 10)}.pdf`);
};


// ============================================================================
//  ENGINEER REPORT
// ============================================================================

export const generateEngineerReport = (projects, division) => {
    const context = { role: 'DepEd Engineer', location: division || 'All Divisions' };
    const { pdf, startY } = createBrandedPDF('Engineer Projects Report', context);

    const tableData = projects.map((p, i) => [
        String(i + 1),
        p.projectName || '—',
        p.schoolName || '—',
        p.status || '—',
        `${p.accomplishmentPercentage || 0}%`,
        p.approved_budget_for_contract || p.projectAllocation ? `₱${Number(p.approved_budget_for_contract || p.projectAllocation).toLocaleString()}` : '—',
        p.contract_amount ? `₱${Number(p.contract_amount).toLocaleString()}` : '—',
        p.targetCompletionDate || '—',
    ]);

    autoTable(pdf, {
        startY,
        head: [['#', 'Project Name', 'School', 'Status', '%', 'ABC', 'Contract Amt', 'Target Date']],
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: [234, 88, 12], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 6.5 },
        bodyStyles: { fontSize: 6.5, textColor: DARK_TEXT },
        alternateRowStyles: { fillColor: [255, 247, 237] },
        margin: { left: 8, right: 8 },
        columnStyles: {
            0: { cellWidth: 7 },
            1: { cellWidth: 35 },
            2: { cellWidth: 30 },
            3: { cellWidth: 20 },
            4: { cellWidth: 10 },
            5: { cellWidth: 22 },
            6: { cellWidth: 22 },
            7: { cellWidth: 20 },
        },
    });

    // Summary footer
    const finalY = pdf.lastAutoTable.finalY + 10;
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...DARK_TEXT);
    pdf.text(`Total Projects: ${projects.length}`, 14, finalY);

    addPageNumbers(pdf);
    pdf.save(`InsightEd_Engineer_Report_${(division || 'All').replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`);
};


// ============================================================================
//  LEADERBOARD REPORT
// ============================================================================

export const generateLeaderboardReport = (rankings, scope, type = 'regions') => {
    const context = { role: 'Leaderboard', location: scope || 'National' };
    const { pdf, startY } = createBrandedPDF(`Leaderboard — ${type.charAt(0).toUpperCase() + type.slice(1)}`, context);

    let tableData;
    let headers;

    if (type === 'schools') {
        headers = [['Rank', 'School Name', 'Division', 'Completion %']];
        tableData = rankings.map((item, i) => [
            String(i + 1),
            item.school_name || item.name || '—',
            item.division || '—',
            `${Math.round(item.completion_rate || item.avg_completion || 0)}%`
        ]);
    } else {
        headers = [['Rank', type === 'regions' ? 'Region' : 'Division', 'Avg. Completion %']];
        tableData = rankings.map((item, i) => [
            String(i + 1),
            item.name || '—',
            `${item.avg_completion || 0}%`
        ]);
    }

    autoTable(pdf, {
        startY,
        head: headers,
        body: tableData,
        theme: 'grid',
        headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
        bodyStyles: { fontSize: 9, textColor: DARK_TEXT },
        alternateRowStyles: { fillColor: LIGHT_BLUE },
        margin: { left: 14, right: 14 },
    });

    addPageNumbers(pdf);
    pdf.save(`InsightEd_Leaderboard_${scope?.replace(/\s+/g, '_') || 'Export'}_${new Date().toISOString().slice(0, 10)}.pdf`);
};


// ============================================================================
//  CSV EXPORT HELPER
// ============================================================================

export const downloadCSV = (data, filename) => {
    if (!data || data.length === 0) return;

    const headers = Object.keys(data[0]);
    const csvRows = [
        headers.join(','),
        ...data.map(row =>
            headers.map(h => {
                const val = String(row[h] ?? '').replace(/"/g, '""');
                return `"${val}"`;
            }).join(',')
        )
    ];

    const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}_${new Date().toISOString().slice(0, 10)}.csv`;
    link.click();
    URL.revokeObjectURL(url);
};
